### PR TITLE
customize composer.json

### PR DESCRIPTION
**Pull request by greg0ire**
Making this package installable with Composer would be great. This is the first step, the second and last would simply be to submit this package to packagist.org

### CODE REVIEW

**Comment by jlong** [comment]
Looks good to me. Added you as a contributor. Please merge.

**Comment by greg0ire** [comment]
@jlong: Could you please create a personal account on packagist.org, so that I can add you as maintainer? Once this is done, you will be able to setup a github hook that will notify packagist.org as soon as you push anything on github. This would be great!

**Comment by jlong** [comment]
Done. I'm jlong on packagist.org.

**Comment by greg0ire** [comment]
And you are now a maintainer. If you go [here](https://packagist.org/packages/jlong/sass-twitter-bootstrap), you'll get a warning explaining how you can make the package "auto-updated". Thank you for your time.

**Comment by jlong** [comment]
Also done.

**Comment by greg0ire** [comment]
Awesome! I going to try to install the package via Composer. If it works, I'll document it. Thanks again.

**Comment by roverwolf** [comment]
Installing via composer now works great.

Fixing the name conflict now allows using a version like ~2.3.0 (which before would update to the official 2.3.1 version instead of staying on the 2.3.0 version of this repository).

**Pull request merged**
