### PR TITLE
update to bootstrap 1.1.1

### PR DESCRIPTION
**Pull request by andreapavoni**

### CODE REVIEW

**Comment by jlong** [comment]
I cherry picked two of the commits from your fork.

Left RVM and rb-fsevent in. One or two things were missed, that I fixed in 79f6cd0b3813f96bd5e33843ba9395d17ceeae14. Also I needed to update the docs based on the latest from Twitter.

Over all though, great work! Did you reconvert everything by had or look at the change log?

Thanks so much!

**Comment by andreapavoni** [comment]
Hi there,

I did everything by hand, starting from the Less sources, and _translating_ syntax to SASS. Now that the port is almost 1:1, next time I think I'll look to the changelog ;-)

cheers

**Comment by jlong** [comment]
It was pretty much a 1:1 port before, but by hand still may be the easiest. There were a lot of changes in the last round.

I found the process of converting from Less to Sass the first time quite interesting. Less has some features that Sass doesn't have. I don't use Less at all, but it was intriguing.

**Comment by andreapavoni** [comment]
me too, I learned a lot from doing this port. I still don't like very much Less, sometimes it has a confusing syntax like ".something()" or "#foo > .bar()" :P

**Pull request closed without merging**
