### PR TITLE
Updates to match v2.0.0

### PR DESCRIPTION
**Pull request by m5o**
based on commit twitter/bootstrap@f68f7870ef of twitter/bootstrap [1]
update scss files groundwork by [2]
diff all files in lib/ against latest twitter/bootstrap (fix some smaller issues)
copy directories docs/ img/ js/
setup symlinks in docs/assets/css/bootstrap*.css
update rake build task

[1] https://github.com/twitter/bootstrap/tree/f68f7870efd4e56dc1d651dc5de37b265558fce1
[2] https://github.com/Brajeshwar/bootstrap-sass-scss-compass

### CODE REVIEW

**Comment by rromanchuk** [comment]
where you at @jlong? lets do this!

**Comment by jlong** [comment]
Hey guys. Haven't had a chance to check this out yet. Really busy this week.

@rromanchuk Does it work well for you?

**Comment by aren55555** [comment]
I really want this to happen!

**Comment by rromanchuk** [comment]
@jlong ill pull down the fork and run against some production apps tonight

**Comment by m5o** [comment]
What i did at the end of the migration. downloaded twitter/bootstrap Version and open it in a Browser Tab. My generated SASS Bootstrap documentation in a second Browser Tab.

Now scrolled, in both tabs to the same content and fast switched the browser tabs to visually see the forgotten bits. Maybe this input helps to make a clear decision.  

Next time i will split my pull request in more logical commits to make this process clearer.

**Comment by jlong** [comment]
@m5o merged this and added you as a collaborator. Please feel free to make additional changes as needed. You've done a great job here. Thanks!

**Comment by rromanchuk** [comment]
thanks @jlong & @m5o

**Comment by m5o** [comment]
thx for the flowers guys!

please also mention @brajeshwar - for his groundwork

**Pull request merged**
