### PR TITLE
Fixed variable syntax error in glyphicons

### PR DESCRIPTION
**Pull request by jslaterTO**

### CODE REVIEW

**Comment by greaterweb** [comment]
Came here to report the gylphicon variable name bug but see that it's been fixed.

Some questions and feedback.

Are the new tags v3.0.0-sass1 and v3.0.0-sass2 meant to replace the v3.0.0 tag?

Though it's not best practice for anything listed as a project dependency but curious if you will ultimately be removing the current v3.0.0 tag and replacing with the final, stable version.

I know the goal is to match the tags with the releases put out by Bootstrap but as there is some work involved in porting it over maybe you could do something like v3.0.0-sass-rc1 and once the issues are ironed out move to v3.0.0 as the final tag.

Either way, keep up the good work. I have been using this repo for all of my recent project work.
- Ron

**Comment by greg0ire** [comment]
The v3.0.0-sass1 is an unsucessful try to get Packagist to make a release. I don't know about the other one.

**Comment by davidolrik** [comment]
@greaterweb What tag would you put on a bug fix which was discovered after the final tag was applied?

I suggested the v3.0.0-sassN to allow any number of sass bug-fix-releases of the twbs/bootstrap v3.0.0.

**Comment by greg0ire** [comment]
If we want composer to work well with this repo, we should name versions like this: v3.0.0.N

**Pull request merged**
