### PR TITLE
Update to 2.0.3

### PR DESCRIPTION
**Pull request by nragaz**
This branch updates everything to 2.0.3 (commit b261f9781bbf31f499cb55c49451dc0c0ad43062 on twitter/bootstrap).

### CODE REVIEW

**Comment by jlong** [comment]
Your last commit (c2ad8e3) is that something 2.0.3 does or your own preference?

**Comment by nragaz** [comment]
That's my own preference, but that was a tweak to 2.0.1 - it's no longer in the 2.0.3 files. I'd just already made that commit on this branch.

**Comment by nragaz** [comment]
Tried to remove that commit via web UI but that's not possible - I'll remove it when I get to my computer.

**Comment by nragaz** [comment]
Removed the extraneous commit.

**Comment by nragaz** [comment]
Responsive grid is broken - working on it now.

**Comment by jlong** [comment]
Thanks Nick. This port is meant to be a direct 1:1 translation from the Less source.

**Comment by nragaz** [comment]
Understood -- that's why I reviewed its output against the compiled LESS output line by line. The commits above don't include anything that's a personal preference.

**Comment by jlong** [comment]
Awesome. Thanks!

**Comment by markushausammann** [comment]
Any idea on when you'll merge this?

**Comment by jlong** [comment]
If @nragaz is ready to merge, I'm all for it.

**Comment by nragaz** [comment]
Yep, all done! Thanks.

**Comment by jlong** [comment]
Merged. Also made you a committer. Please feel free to make additional updates.

Thanks!

**Comment by markushausammann** [comment]
Thanks guys! This is really a great port... I don't understand why TB isn't based on SASS in the first place anyways.

**Comment by peschee** [comment]
The `VERSION` file still states 2.0.2 for this PR. Shouldn't that be 2.0.3?

**Comment by jlong** [comment]
It looks like it's 2.0.3 to me.

**Comment by jlong** [comment]
The Makefile should be removed though. This version uses Rake.

**Comment by nragaz** [comment]
The Makefile is useful for running the new JS tooling added in 2.0.3 - should that be ported in to the Rakefile, or should we remove the LESS could from the Makefile and include both?

**Pull request merged**
