### PR TITLE
Updates it to match v1.4.0

### PR DESCRIPTION
**Pull request by rrjamie**
Hello,

I went ahead an trawled through the diffs on the Twitter Bootstrap less version, and made the corresponding changes to the SCSS version. I think it's pretty close.

Cheers,

Ryan

### CODE REVIEW

**Comment by jlong** [comment]
I've added you as a collaborator. Please be sure that the docs render identically to the Less version of the Twitter bootstrap docs. Then merge when you are ready.

Thanks!

**Comment by rrjamie** [comment]
One thing I did actively remove was the "--webkit-transform-style: preserve-3d" property which impacts the rendering of non-square element (chiefly form elements, checkboxes). It is also removed from Bootstrap's master branch.

**Comment by silvenon** [comment]
While you're at it, there's a typo in the `makeColumn` mixin you can fix (`@include columns($columnSapn);`). Thanks for doing this! When do you think you'll be done? :)

**Comment by rrjamie** [comment]
Good catch.

The docs look identical (only one small fix need), with the exception of Chrome's issues with "preserve-3d" (which manifests on the LESS version, but I removed from the SCSS version).

**Comment by silvenon** [comment]
Whoa, I wasn't expecting it **this** soon! :)

**Pull request merged**
