### PR TITLE
// removed Invalid US-ASCII character "\xE2"

### PR DESCRIPTION
**Pull request by Shipow**
error stylesheets/bootstrap/bootstrap.scss (Line 79 of
stylesheets/bootstrap/_grid.scss: Invalid US-ASCII character "\xE2")

### CODE REVIEW

**Comment by m5o** [comment]
duplicate of #97 

you should report this to the upstream repo [twbs/bootstrap](https://github.com/twbs/bootstrap)

**Comment by Shipow** [comment]
ok i'll do
thank you for your work.

**Comment by Shipow** [comment]
PR have been merged on https://github.com/twbs/bootstrap/pull/10336

**Comment by kenjiqq** [comment]
We had this same issue, would be cool if it could be accepted

**Comment by swis** [comment]
:+1: for real dashes.

**Pull request merged**
