### PR TITLE
remove jquery dependency

### PR DESCRIPTION
**Pull request by lanterndev**
Not all users need JQuery to achieve bootstrap's javascript functionality. They could be using https://github.com/angular-ui/bootstrap instead for example. This change leaves it up to the user to specify the JQuery dependency if she needs it.

### CODE REVIEW

**Comment by greg0ire** [comment]
> No, because this package is only for the styles, not the javascript functionality.

What makes you say that ? Why wouldn't this package be for both the styles and the javascript functionality ?

**Comment by lanterndev** [comment]
I read "This project is focused on being a 1:1 translation from Less to Sass" on https://github.com/jlong/sass-twitter-bootstrap and assumed that's all it had in it, similar to how projects like https://github.com/vwall/compass-twitter-bootstrap only deal with the styles.

Now I see you're also including the javascript too, sorry I missed that. I assume you're not changing any of the upstream javascript though, it's just there so this can be one-stop shopping for all of bootstrap. In a more perfect world I think the bootstrap styles provider and the bootstrap javascript provider would be separated so that you could choose between e.g. less vs. sass versions of the former, or angular vs. vanilla versions of the latter.

**Comment by jlong** [comment]
Sorry guys. 1:1 means exactly like Bootstrap, but with Sass. If you want to get jQuery removed from Bootstrap you should do so upstream in the Less version.

**Comment by ryanburnette** [comment]
I have to agree with @jlong. I look to this repository to be exactly what Bootstrap is, just in Sass rather than Less. In many cases I omit the Javascript entirely, but when doing that I don't feel that I am using Bootstrap. I am using part of Bootstrap.

You could consider making a repo that contains a build script which pulls in this repo and angular as submodules then smash up the parts you want from each repo. I think that would be pretty cool. You'd clone, init submodules, run the build script then voila. I'd even be down to contribute to its creation.

**Pull request closed without merging**
