### PR TITLE
Updating to 1.2 (or as much as possible)

### PR DESCRIPTION
**Pull request by krainboltgreene**

### CODE REVIEW

**Comment by krainboltgreene** [comment]
I did as much as I could that didn't involve transporting logic. The stuff that does require that kind of work is here: https://gist.github.com/1205549

Also, the adaptive.less file needs porting.

In addition I propose a switch to the = and + syntax for mixins and includes.

**Comment by JeanMertz** [comment]
Great job. I hope this gets pulled in soon. I was considering switching to LESS for my new project just so I can use the beautiful `bootstrap` designs, but I am too much invested in `sass` to make that switch. I hope this keeps getting enough love.

**Comment by krainboltgreene** [comment]
Rails is pretty invested in `sass` too it turns out. I had nothing but trouble getting Rails to use less in any capacity beyond manually compiling the sheets. `less.gem` is a joke.

**Comment by krainboltgreene** [comment]
Is this needed with Pull Request #8?

**Comment by copiousfreetime** [comment]
I don't think so. I imagine its fine to close this one. I just merged #8.

**Comment by benatkin** [comment]
@krainboltgreene I realize it's been over a month since you posted that comment, but I found that https://github.com/metaskills/less-rails worked right away after I got therubyracer installed (which was difficult but only because I had multiple versions of scons on my machine that were conflicting with the scons included in the libv8 gem).

**Comment by krainboltgreene** [comment]
Hmm, maybe I had problems with therubyracer? Ho hum.

**Comment by benatkin** [comment]
@krainboltgreene I wouldn't be surprised if you ran into a similar issue to what I ran into. Uninstalling all versions of Scons (libv8 has its own) totally fixed it for me.

**Pull request closed without merging**
